### ISSUE TITLE
What is the standard way to add the result to the data set as new columns?

### ISSUE THREAD

**Issue by Superhzf** [limexp/xgbfir#3]
Thanks for your code, it is really helpful!

I would like to know what is the standard way to add the interactions to the original data set? Suppose I know the interaction between Petal Length and Petal Width is important, how can I use this information in the data set? 

Just try new columns like Petal Length*Petal Width or Petal Length/Petal Width, is it a good way? What if there is a relationship between a categorical variable and a numerical variables?

Thanks!

**Comment by zachwill** [comment]
I believe simple pairwise interactions are the best bet? [Link to @Far0n's code](https://github.com/Far0n/kaggle-homesite/blob/master/top15_homesite_xgb.py#L228-L237) from a couple years ago, where he simply used subtraction between features. [Matt VonRohr also advocated](http://people.inf.ethz.ch/jaggim/meetup/slides/ML-meetup-9-vonRohr-kaggle.pdf) for simple pairwise interactions (multiplication, division, subtraction, addition).

**Comment by zachwill** [comment]
Another one of [Far0n's comments on Kaggle](https://www.kaggle.com/c/bnp-paribas-cardif-claims-management/discussion/18754#113908) that I found useful:

> When XGB reports something like `F1|F2` it already models "*something*" between `F1` and `F2`. That does not tell us whether any of `F1 (+|-|*|/) F2` would be useful, because with `A (+|-|*|/) B` we want to add something what XGB is not capturing, but for obvious reasons XGB is not telling us what that could be.
