### ISSUE TITLE
Code refactoring?

### ISSUE THREAD

**Issue by zachwill** [limexp/xgbfir#6]
Hey @limexp,

First off: awesome work on this! The fact that you were able to translate C# to Python — and carry over all the features from [`xgbfi`](https://github.com/Far0n/xgbfi) — is really impressive. 👏 

I was wondering if you'd be cool with major refactoring of the code? I'd love to translate most of it over to [PEP 8](https://www.python.org/dev/peps/pep-0008/) and introduce unit tests.

I only ask outright because it'd involve quite a lot of renaming functions/methods/classes.

Zach

**Comment by limexp** [comment]
Hey @zachwill,

Thank you!

I had a hard year, so didn't pay due attention to this project.

The code base is not big, so there is no problem in refactoring. But one of the difficult questions from the very beginning was the choice of the right interface. it would be great if you share your wishes and remarks.

I'll set up CI this week and start refactoring after this.

Boris

**Comment by zachwill** [comment]
Moving the conversation over to pull request #7.
